#!/bin/sh
set -e

remove() {
    for i in 0 1
    do
        systemctl stop oi-lab-xorg-daemon@${i}.service || true
        systemctl stop oi-lab-xorg-daemon@${i}.socket || true
        systemctl disable oi-lab-xorg-daemon@${i}.socket || true
    done
}

case "$1" in
    remove|deconfigure)
        remove
	;;

    upgrade|failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
esac
