#!/bin/sh
set -e

action=${1}
version=${2}

for fragment in lxsession/Lubuntu/desktop.conf lxsession/Lubuntu-Netbook/desktop.conf menus/lxlauncher-applications.menu
do
    conf="/etc/xdg/${fragment}"
    conf_divert="${conf}.original"

    if [ upgrade != "${action}" ] || dpkg --compare-versions "${version}" lt 0.0.1
    then
        dpkg-divert --package oi-lab-lubuntu-extra-settings --divert ${conf_divert} --rename --add ${conf}
    fi
done
