#!/bin/sh
set -e

install() {
    for i in 0 1
    do
        systemctl enable oi-lab-xorg-daemon@${i}.socket
        systemctl start oi-lab-xorg-daemon@${i}.socket
    done

    udevadm trigger
}

case "${1}" in
    configure)
        install "${2}"
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`${1}'" >&2
        exit 1
        ;;
esac
