#!/bin/bash

# Copyright (C) 2017 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This file is part of le-multiterminal
#
# le-multiterminal is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

#### Description: A wrapper for the multi-seat configurator.
#### Checks the need to reconfigure / configure the multi-terminal and restarts the system.
#### Written by: Thiago Abdo - tja14@c3sl.ufpr.br on 2017.
#### Modified by: Laércio de Sousa - laerciosousa@sme-mogidascruzes.sp.gov.br on 2018.

set -x
####LOGFILE
LOGDIR=/var/log/oi-lab-multi-seat-config
if test ! -d $LOGDIR; then
    mkdir -p $LOGDIR
fi

CONFIG_FLAG=0

for i in /etc/udev/rules.d/72-seat-*; do
    if test ! -e $i; then
        CONFIG_FLAG=1
    fi

    break
done

if test $CONFIG_FLAG -eq 1; then
    /usr/sbin/oi-lab-multi-seat-controller >> $LOGDIR/controller.log 2>&1
fi
