#!/bin/bash

num_users=${1:-5}
freeze_template_user="freezetemplate"
freeze_template_fullname="Modelo para Freeze"

if ! getent group freeze >/dev/null
then
    addgroup freeze
fi

if ! getent passwd ${freeze_template_user} >/dev/null
then
    adduser --disabled-login --gecos "${freeze_template_fullname}" --shell /bin/bash ${freeze_template_user}
    echo "${freeze_template_user}:freeze" | chpasswd
fi

su ${freeze_template_user} -c "env LANG=pt_BR.UTF-8 xdg-user-dirs-update"
su ${freeze_template_user} -c "[ -d ~/.config/autostart ] || mkdir ~/.config/autostart || exit 1"
su ${freeze_template_user} -c "echo -e '[Desktop Entry]\nType=Application\nName=Autostart commands for freeze sessions\nExec=oi-lab-freeze-session-auto' > ~/.config/autostart/oi-lab-freeze-session-auto.desktop"

for i in blueman light-locker print-applet update-notifier xfce4-power-manager
do
    su ${freeze_template_user} -c "echo -e '[Desktop Entry]\nHidden=true' > ~/.config/autostart/${i}.desktop"
done

for i in $(seq -w 0 $(( num_users - 1 )))
do
    username="aluno${i}"
    fullname="Aluno #${i}"

    if ! getent passwd ${username} >/dev/null
    then
        adduser --disabled-login --gecos "${fullname}" --shell /bin/bash ${username}
        adduser ${username} freeze
        echo "${username}:${username}" | chpasswd
    fi
done

for dir in documents music pictures videos
do
    mkdir -p -m0777 /var/freeze-data/${dir}
done

if ! [ -f /etc/lightdm/lightdm.conf.d/10-oi-lab-autologin.conf ]
then
    [ -d /etc/lightdm/lightdm.conf.d ] || mkdir -p /etc/lightdm/lightdm.conf.d
    cat >>/etc/lightdm/lightdm.conf.d/10-oi-lab-autologin.conf <<EOF
#[Seat:*]
#autologin-user-timeout=60

#[Seat:seat0]
#autologin-user=aluno00

#[Seat:seat-sm501-0-lvds]
#autologin-user=aluno01

#[Seat:seat-sm501-0-vga]
#autologin-user=aluno02

#[Seat:seat-sm501-1-lvds]
#autologin-user=aluno03

#[Seat:seat-sm501-1-vga]
#autologin-user=aluno04
EOF
fi
