#!/bin/bash

num_users=${1:-5}
freeze_template_user="freezetemplate"

for i in $(seq -w 0 $(( num_users - 1 )))
do
    username="aluno${i}"

    if getent passwd ${username} >/dev/null
    then
        deluser ${username}
    fi

    rm -rf /home/${username}
done

if getent passwd ${freeze_template_user} >/dev/null
then
    deluser ${freeze_template_user}
fi

rm -rf /home/${freeze_template_user}

if getent group freeze >/dev/null
then
    delgroup freeze
fi

rm -rf /var/freeze-data
